version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8450}:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ".:/app"
      - "/app/node_modules"
